-- Custom types
create type public.member_roles as enum ('owner', 'member', 'deleted');

-- USERS
create table public.users (
  id            uuid not null primary key, -- UUID from auth.users
  displayName   text,
  email         text,
  photoURL      text,
  bio           text,
  defaultWorkspaceId uuid,
  createdAt     timestamp with time zone default timezone('utc'::text, now()) not null,
);
comment on table public.users is 'Profile data for each user.';
comment on column public.users.id is 'References the internal Supabase Auth user.';

-- WORKSPACE
create table public.workspaces (
  id            uuid generated by default as identity primary key,
  name          text not null,
  isDeleted     boolean not null default false,
  createdAt     timestamp with time zone default timezone('utc'::text, now()) not null,
);
comment on table public.workspaces is 'A workspace represents a group of users.';

-- MEMBER
create table public.members (
  id            uuid generated by default as identity primary key,
  role          member_roles not null,
  workspaceId   uuid references public.workspaces on delete cascade not null,
  memberId      uuid references auth.users on delete cascade not null,
  createdAt     timestamp with time zone default timezone('utc'::text, now()) not null,
);
comment on table public.member is 'Stores the user to workspace relationship';

-- INVITE
create table public.invites (
  id            uuid generated by default as identity primary key,
  workspaceId   uuid references public.workspaces on delete cascade not null,
  inviterId     uuid references auth.users not null,
  email         text not null,
  createdAt     timestamp with time zone default timezone('utc'::text, now()) not null,
);
comment on table public.member is 'Stores the user to workspace relationship';
